services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
